### GET ALL CONTACTS
GET http://localhost:3001/author

### GET CONTACT BY ID
GET http://localhost:3001/author/{67e4ee534620a30c04cc91a4}

### CREATE CONTACT
POST http://localhost:3001/author
Content-Type: application/json

{
    "name": "Chinwa oojjkahs",
    "books": "Thongd fall Apart",
    "completion": "completed",
    "publishedYear": "2022",
    "dob": "12-34-2024"
}

### UPDATE CONTACT
PUT http://localhost:3001/author/67e4ee534620a30c04cc91a4
Content-Type: application/json

{
     "name": "emms",
    "books": "ddd",
    "completion": "completed",
    "publishedYear": "1825",
    "dob": "16-02-22"
}

### DELETE CONTACT
DELETE http://localhost:3001/author/67e519873e1158280ee03bf4

